### ISSUE TITLE
DaemonSet test failing

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#118]
Currently, the `DaemonSet` e2e test is failing:

```
Running end-to-end tests...
time="2018-11-20T13:25:34+01:00" level=info msg="passing &{{Jaeger io.jaegertracing/v1alpha1} {agent-as-daemonset  jaeger-jaeger-group-daemonset-1542716724    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {allInOne { {map[]} {[] [] map[] {map[] map[]}}} {0  {map[]} {[] [] map[] {map[] map[]}}} {0  {map[]} {[] [] map[] {map[] map[]}}} {DaemonSet  {map[log-level:debug]} {[] [] map[] {map[] map[]}}} { {map[]} {<nil>   }} {<nil>  {[] [] map[] {map[] map[]}}} {[] [] map[] {map[] map[]}}} {}}"
time="2018-11-20T13:27:05+01:00" level=info msg="passing &{{Jaeger io.jaegertracing/v1alpha1} {with-cassandra  jaeger-jaeger-group-cassandra-1542716820    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {allInOne { {map[]} {[] [] map[] {map[] map[]}}} {0  {map[]} {[] [] map[] {map[] map[]}}} {0  {map[]} {[] [] map[] {map[] map[]}}} {  {map[]} {[] [] map[] {map[] map[]}}} {cassandra {map[cassandra.servers:cassandra.default.svc]} {<nil>   }} {<nil>  {[] [] map[] {map[] map[]}}} {[] [] map[] {map[] map[]}}} {}}"
time="2018-11-20T13:27:30+01:00" level=info msg="passing &{{Jaeger io.jaegertracing/v1alpha1} {my-jaeger  jaeger-jaeger-group-my-other-jaeger-1542716840    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {allInOne { {map[log-level:debug memory.max-traces:10000]} {[] [] map[] {map[] map[]}}} {0  {map[]} {[] [] map[] {map[] map[]}}} {0  {map[]} {[] [] map[] {map[] map[]}}} {  {map[]} {[] [] map[] {map[] map[]}}} { {map[]} {<nil>   }} {<nil>  {[] [] map[] {map[] map[]}}} {[] [] map[] {map[] map[]}}} {}}"
time="2018-11-20T13:27:30+01:00" level=info msg="passing &{{Jaeger io.jaegertracing/v1alpha1} {my-jaeger  jaeger-jaeger-group-my-jaeger-1542716840    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {allInOne { {map[memory.max-traces:10000 log-level:debug]} {[] [] map[] {map[] map[]}}} {0  {map[]} {[] [] map[] {map[] map[]}}} {0  {map[]} {[] [] map[] {map[] map[]}}} {  {map[]} {[] [] map[] {map[] map[]}}} { {map[]} {<nil>   }} {<nil>  {[] [] map[] {map[] map[]}}} {[] [] map[] {map[] map[]}}} {}}"
--- FAIL: TestJaeger (151.38s)
    --- FAIL: TestJaeger/jaeger-group (115.68s)
        --- FAIL: TestJaeger/jaeger-group/daemonset (70.16s)
            client.go:57: resource type Role with namespace/name (jaeger-jaeger-group-daemonset-1542716724/jaeger-operator) created
            client.go:57: resource type RoleBinding with namespace/name (jaeger-jaeger-group-daemonset-1542716724/default-account-jaeger-operator) created
            client.go:57: resource type Deployment with namespace/name (jaeger-jaeger-group-daemonset-1542716724/jaeger-operator) created
            jaeger_test.go:50: Initialized cluster resources
            wait_util.go:45: Waiting for full availability of jaeger-operator deployment (0/1)
            wait_util.go:51: Deployment available (1/1)
            client.go:57: resource type Jaeger with namespace/name (jaeger-jaeger-group-daemonset-1542716724/agent-as-daemonset) created
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            daemonset.go:29: timed out waiting for the condition
            client.go:75: resource type Jaeger with namespace/name (jaeger-jaeger-group-daemonset-1542716724/agent-as-daemonset) successfully deleted
            client.go:75: resource type Deployment with namespace/name (jaeger-jaeger-group-daemonset-1542716724/jaeger-operator) successfully deleted
            client.go:75: resource type RoleBinding with namespace/name (jaeger-jaeger-group-daemonset-1542716724/default-account-jaeger-operator) successfully deleted
            client.go:75: resource type Role with namespace/name (jaeger-jaeger-group-daemonset-1542716724/jaeger-operator) successfully deleted
FAIL
FAIL	github.com/jaegertracing/jaeger-operator/test/e2e	151.460s
```

According to `git bisect`:

```
13d7cc5db1b3b9effbd262e9f0e77d8a1b76d139 is the first bad commit
commit 13d7cc5db1b3b9effbd262e9f0e77d8a1b76d139
Author: Juraci Paixão Kröhling <juraci.github@kroehling.de>
Date:   Tue Nov 13 16:29:46 2018 +0100
```

**Comment by objectiser** [comment]
Strange - that commit is mainly doc/changelog changes - except the jaeger version moves from 1.7 to 1.8. I assume the e2e tests would pick up the version from that `jaeger.version` file?

**Comment by pavolloffay** [comment]
is e2e using agent?

**Comment by jpkrohling** [comment]
> is e2e using agent?

Not quite sure I understand the question. There's an e2e test with the agent as DaemonSet (the one that is failing), but there's also a test with the agent as side-car.

**Comment by dlmiddlecote** [comment]
Follow up:
The readiness probe failing is caused by the `/metrics` endpoint not being available, which in turn is caused by the agent HTTP Server not being started. This was fixed in [this PR](https://github.com/jaegertracing/jaeger/pull/1178).
The `jaegertracing/jaeger-agent:1.8` image does not have this fix, but `jaegertracing/jaeger-agent:latest` does.
I've tried with this image allows the agent to become available.

Not sure if that really helps with this problem, but I thought I'd mention it, as it helps me, and maybe others.

**Comment by jpkrohling** [comment]
This is a nice detective work, @dlmiddlecote! 

@pavolloffay: did you end up releasing 1.8.1 with the fix from jaegertracing/jaeger#1178

**Comment by jpkrohling** [comment]
For the record, the image for 1.8 is still the same as 1.8.0. I expect the 1.8 tag to point to 1.8.1 once that's released.

https://hub.docker.com/r/jaegertracing/jaeger-agent/tags/

**Comment by pavolloffay** [comment]
Not yet I am waiting for https://github.com/jaegertracing/jaeger-ui/pull/263

**Comment by jpkrohling** [comment]
Alright, I'll remove the readiness check then, as it might take a couple of days for that to get merged.

**Comment by dlmiddlecote** [comment]
@jpkrohling is there anything else you can use as a Readiness probe/Liveness probe? 
Is there a way to see if the agent is connected to the collector, as that’s what the agent really needs, not just the fact that metrics are being exposed.

**Comment by jpkrohling** [comment]
I'll check, but IIRC, the agent is pretty much the only component without the health check handler:

https://github.com/jaegertracing/jaeger/blob/f2eb7d14902909d2ace35b224f0c1e32519caf6f/cmd/agent/app/httpserver/server.go#L37-L50

And for the all-in-one, note how we create the `hc` and pass to `collector` and `query`, but not `agent`:

https://github.com/jaegertracing/jaeger/blob/f2eb7d14902909d2ace35b224f0c1e32519caf6f/cmd/all-in-one/main.go#L98

https://github.com/jaegertracing/jaeger/blob/f2eb7d14902909d2ace35b224f0c1e32519caf6f/cmd/all-in-one/main.go#L132-L135

This would be a nice feature request, I believe. Would you mind opening an issue on the main repo (jaegertracing/jaeger)?

**Comment by dlmiddlecote** [comment]
Thanks for the explanation! I can open the issue, to add a healthcheck to the agent.

What are the next steps for this? Removing the readiness probe and releasing a new version of the operator chart?

**Comment by jpkrohling** [comment]
> operator chart

Did you mean this repo here? If so, I can certainly release a patch version this afternoon.

**Comment by jpkrohling** [comment]
@dlmiddlecote 1.8.1 is out. Let me know if it looks alright to you.

**Comment by dlmiddlecote** [comment]
@jpkrohling Looks good, thanks for the speedy turn-around.

**Comment by kevinearls** [comment]
@jpkrohling I think you can close this.  It currently runs on Kubernetes, and remaining issues on OpenShift are being tracked by https://github.com/jaegertracing/jaeger-operator/issues/178
